### ISSUE TITLE
Refactor printing in CLI

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-cli-js#118]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Not good structured output from CLI

* **What is the expected behavior?**
Have an consistent outpur for CLI\

**Comment by davidyuk** [comment]
the description doesn't sound clear from now, I'm fixing all inconsistencies I finding
