### ISSUE TITLE
Allow an easier way to provide amounts

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-cli-js#119]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

currently, you have to specify all the amounts in aettos (1e18) for any tx that involves token amount

* **What is the expected behavior?**

it would be nice to be able to specify amounts in a more human-readable way, especially for the cli but also in other contexts.

for example allow to spcify amount like:
- 5ae    = 500000000000000000
- 1.5ae = 150000000000000000
- 0.5     = 50000000000000000

* **What is the motivation/use case for changing the behavior?**
it is somewhat cumbersome and error-prone to have to count the 0s

* **Please tell us about your environment:**
  
  - SDK Version: v6.0.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

**Comment by davidyuk** [comment]
implemented in #201
