### ISSUE TITLE
Some commands are unreasonable slow

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-cli-js#139]
```bash
$ time node bin/aecli.js --version
2.6.0
node bin/aecli.js --version  0.71s user 0.13s system 118% cpu 0.710 total
$ time npm --version              
6.14.4
npm --version  0.14s user 0.03s system 108% cpu 0.155 total
```

So, on my computer, showing a version ~5 times slower for cli than to npm. It has a user experience like cli makes a network request or so. It would be nice to have it working as fast as possible especially when user requests `--help` instead of making an actual action.

**Comment by dincho** [comment]
I can confirm, supper slow times.
