### ISSUE TITLE
JSON output mode is needed only for tests?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-cli-js#140]
If yes, I proposing to find a different solution without extra interfaces for the end-user. In general, the idea to keep output parsable (using grep/awk and so on), but if the user wants to work specifically with json then he may probably use sdk instead.

**Comment by dincho** [comment]
No please. It's very helpful in automated scripts. Other structured approach is also acceptable like AWS CLI --query param.

**Comment by davidyuk** [comment]
> No please. It's very helpful in scripted automation.

Ok, got it

> Other structured approach is also acceptable like AWS CLI --query param.

Do you mean it as an additional feature to JSON output? It should be enough to use an extra tool for querying like `jq`:
```
$ ./bin/aecli.js chain status --json | jq ".protocols[2:4]"
[
  {
    "effectiveAtHeight": 82900,
    "version": 3
  },
  {
    "effectiveAtHeight": 40900,
    "version": 2
  }
]
```

**Comment by dincho** [comment]
I'm indeed using JSON + jq right now. I meant that in case you insist on dropping the JSON output and alternative approach should be provided AWS CLI like query.
