### ISSUE TITLE
Ask for password from stdin in case it wasn't provided in arguments and env

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-cli-js#142]
I assume that it is super insecure because of `.bash_history` and so on.

**Comment by nduchak** [comment]
Good point! But it was added to allow users to have some bash scripts or something which can integrate/automate the CLI commands(if they don't want to use SDK)?
Not sure that is still the valid case so we probably need to remove this

**Comment by davidyuk** [comment]
I propose to use the approach similar to `GIT_ASKPASS`/`SSH_ASKPASS`.
https://git-scm.com/docs/gitcredentials#_requesting_credentials

**Comment by dincho** [comment]
Please don't break automation because of stupid users.

**Comment by davidyuk** [comment]
@dincho I believe you have more experience here, what is the best way to accept passwords in cli?

**Comment by dincho** [comment]
Keeping it as argument should be fine, clever users could hide a command from bash history by prefixing it with "space".
I haven't looked the CLI implementation but accepting an environment variable for most common arguments would also improve the experience.

Asking for password from stdin is okay for interactive workflow, but not for automation.

**Comment by davidyuk** [comment]
actually, this is already implemented: https://github.com/aeternity/aepp-cli-js/blob/ec7ace88b4b32d9bdd07eb44a074c19e8c0f1e63/bin/utils/account.js#L64
