### ISSUE TITLE
Contract cannot be deployed with bytecode only

### ISSUE THREAD

**Issue by dincho** [aeternity/aepp-cli-js#167]
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

```
➜  aecli contract deploy --json -P "CHANGE_ME_NOW" --networkId ae_uat wallets/dev build/contracts/Example2.aeb "cb_KxFE1kQfP4oEp9E="
API ERROR:  
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The above should be enough, try with any contract.

* **What is the expected behavior?**

No error, the same output as if deploying with source.

* **What is the motivation / use case for changing the behavior?**
There is no point requiring the contract source code because the actual node API accepts a bytecode. This adds duplicate compilation step.

* **Please tell us about your environment:**
  
Unrelated. CLI version is 3.0.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

As guessing if it's bytecode or source code from file name or file contents would be tedious and error prone, and additional option to switch to bytecode instead of source code should be added. Also for BC.

**Comment by marc0olo** [comment]
not sure if it's a bug. I guess nobody requested this before. will mark it as enhancement 😅 

> As guessing if it's bytecode or source code from file name or file contents would be tedious and error prone, and additional option to switch to bytecode instead of source code should be added.

I also prefer the option here. we should expect sourcecode by default and bytecode when option is provided

> Also for BC.

what do you mean with that?
