### ISSUE TITLE
Use mainnet by default

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-cli-js#178]

**Comment by marc0olo** [comment]
@davidyuk why would you want to use mainnet by default? I actually like that testnet is the default config

**Comment by davidyuk** [comment]
Maybe to make user explicitly switch to testnet, otherwise he may not know that he is working with testnet data. There are tools that using mainnet/production by default, like our wallets or even webpack. Also, permanent switching between networks should be easy after megring #213

Switching to mainnet doesn't make sence if cli is not intended to use in mainnet, but I think it does 🤔 

Mainnet is the only one, we can have multiple testnets like in ethereum.

**Comment by marc0olo** [comment]
> Switching to mainnet doesn't make sence if cli is not intended to use in mainnet, but I think it does 🤔

we should definitely clearly state that in the release if we change the default behavior. I would even provide that information somewhere when calling the `help` command.

> Mainnet is the only one, we can have multiple testnets like in ethereum.

true

**Comment by davidyuk** [comment]
implemented in 5a81814bf39e156e00e8f8c6ed6d903770725446
