### ISSUE TITLE
error in (static) contract call not handled properly

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-cli-js#209]
we just had a bug report on Discord (#hackathon-chat):

![image](https://user-images.githubusercontent.com/8124114/187945249-4e5ecac2-01c8-4ce5-92f4-6d2a60c4c89f.png)

problem is with default contract in AEstudio where the `receiver` map doesn't include any values. when calling `checkUserBalance` this leads to an error. we should return meaningful data in this case.

see https://github.com/aeternity/fire-editor/blob/master/src/app/contracts/AeForUsers.aes

**Comment by davidyuk** [comment]
> problem is with default contract in AEstudio where the receiver map doesn't include any values. when calling checkUserBalance this leads to an error

> NodeInvocationError: Invocation failed: "Maps: Key does not exist"

do you mean this one? The only thing to improve is to don't show the stack trace

Calling by
```
$ aecli contract call --contractSource ./AeForUsers.aes --contractAddress ct_x1gAeyEBthWUZxkKXgXSunCrJdPfiM32Z9yQjHrJcTxqM385g --callStatic checkUserBalance "[]" wallet.json
```
returns the expectation mentioned above, not "Unexpected token c in JSON", on develop branch.

In general the "Unexpected token c in JSON" is because of invalid order of arguments (it tries to parse `checkUserBalance` or so as json), also is there only a single `-` before `contractAddress` on screenshot?

**Comment by marc0olo** [comment]
> also is there only a single `-` before `contractAddress` on screenshot?

good question, would have to ask the reporter. but comparing with `contractSource` option it seems like it's a single `-` 🤔 

=> assuming it is a single `-`, would that be the reason for the command to behave like see in the screenshot?

> > NodeInvocationError: Invocation failed: "Maps: Key does not exist"
> 
> do you mean this one?

yeah if this is printed it's fine. maybe I confused things here as I played around a lot with CLI in this moment.

**Comment by davidyuk** [comment]
> would that be the reason for the command to behave like see in the screenshot?

yes, or the wrong order of argument, it depends on is it a develop version or 4.1.0

**Comment by marc0olo** [comment]
he used  `4.1.0` afaik
