### ISSUE TITLE
aepp-cli-js update to Release 2.0.0, aecli can not use?

### ISSUE THREAD

**Issue by Alteryy** [aeternity/aepp-cli-js#77]
bin/aeternity versions Installed versions:* 3.0.1 permanent
aecli --version 2.0.0

when i use: aecli account spend …
the result is : Unsupported node version 3.0.1. Supported: >= 1.4.0 < 3.0.0 undefined
thx.

**Comment by nduchak** [comment]
⚠ 🚀 AEPP-CLI 2.1.0 is out
⚠⚠⚠ Fortuna Compatibility ⚠⚠⚠
Install it with ` npm install @aeternity/aepp-cli`
