### ISSUE TITLE
`tx broadcast` asks for password

### ISSUE THREAD

**Issue by ricricucit** [aeternity/aepp-cli-js#9]
`tx broadcast` asks for password, but it shouldn's...because the TX is already signed.

**Comment by nduchak** [comment]
@ricricucit Sorry, but i can not repro this.

**Comment by ricricucit** [comment]
This was coming from a conversation with @noandrea . @noandrea can you explain?

**Comment by nduchak** [comment]
It's strange. I have checked the code and we don't have place where we prompt for pass...)
