### ISSUE TITLE
Unsupported node version 4.0.0. Supported: >= 3.0.1 < 4.0.0 undefined

### ISSUE THREAD

**Issue by itinance** [aeternity/aepp-cli-js#91]
Running `aecli account balance` ends up with old node version error message:

`aecli account balance /data/workspace/aeternity/dev/ae-certification/itinance -u https://sdk-testnet.aepps.com`

gives:

> ✔ Enter your password … *********************************************************
> Unsupported node version 4.0.0. Supported: >= 3.0.1 < 4.0.0 undefined
> 

However, its been a while that I dealt with node 4. My node version is: 

♠ node -v
v10.16.0

♠ aecli --version
2.1.0

Any ideas?

**Comment by nduchak** [comment]
@itinance Hello,
You just need to update `aepp-cli` to lates version
Here is changelog: https://github.com/aeternity/aepp-cli-js/releases/tag/2.2.0

**Comment by itinance** [comment]
Hey @nduchak Thanks for fast reply. I've already found out that there is a new version available :) It works!
